services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-app
        volumes:
            - ./laravel:/var/www/laravel
        networks:
            - app-network
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - PHP_OPCACHE_MEMORY_CONSUMPTION=128
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.2
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: home_portal_v2
            MYSQL_USER: app_user
            MYSQL_PASSWORD: app_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis-cache
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx-web
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./laravel:/var/www/laravel
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - F:/Images:/usr/share/nginx/photos:ro
        networks:
            - app-network
        depends_on:
            - app

volumes:
    mysql_data:

networks:
    app-network:
        driver: bridge