# nginx/conf.d/app.conf
server {
    listen 80;
    server_name docker-porto.loc;

    root /var/www/laravel/public;
    index index.php index.html;

    client_max_body_size 50M;

    location ^~ /windows/images/ {
        alias /usr/share/nginx/images/;
        autoindex on;
        access_log /var/log/nginx/images_access.log;
        error_log /var/log/nginx/images_error.log debug;
        log_not_found on;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Laravel Reverb (Pusher protocol) — /app/{key}
    location ^~ /app {
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://php-app:8080;
    }

    location ~ \.php$ {
        fastcgi_pass   php-app:9000;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME /var/www/laravel/public$fastcgi_script_name;
        fastcgi_param  PATH_INFO $fastcgi_path_info;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}